name: Verificação de README

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Verificar sintaxe do README.md
        run: test -f README.md && echo "README.md OK"
